### ISSUE TITLE
When an item is sold or traded it still is linked to the (last) owner

### ISSUE THREAD

**Issue by Lukasmaes** [Step7750/CSGOFloat-DB#2]
This is rather dissapointing. Found a couple interesting items through the database lately and when I clicked the profile link they didn't have that item anymore. I don't see use in linking wrong profile to items that are not in that inventory anymore! Just a suggestion! Thanks for the great website though

**Comment by Step7750** [comment]
This is an inherit caveat to any third party database. We simply can't just refresh 10's of millions of inventories fast enough to be fully up to date all the time. Showing stale data however is still preferred to no data, not that we'd be able to easily detect stale inventories anyways.
